int a = 12561;
int b = 23514;
int c = 55556;
int d = 11119;
int e = 12128;
int max = a;
if(a > max) max = a;
if(b > max) max = b;
if(c > max) max = c;
if(d > max) max = d;
if(e > max) max = e;
Console.Write("max = ");
Console.WriteLine(max);